//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Diciplines = new HashSet<Dicipline>();
        }
    
        public int CatID { get; set; }
        public string CategoryEng { get; set; }
        public string CategoryArb { get; set; }
    
        public virtual ICollection<Dicipline> Diciplines { get; set; }
    }
}
