//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        public Degree()
        {
            this.Programs = new HashSet<Program>();
        }
    
        public int DegreeID { get; set; }
        public string DegreeEng { get; set; }
        public string DegreeArb { get; set; }
    
        public virtual ICollection<Program> Programs { get; set; }
    }
}
