//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public Faculty()
        {
            this.FacultyComments = new HashSet<FacultyComment>();
            this.Programs = new HashSet<Program>();
        }
    
        public long FacultyID { get; set; }
        public string FacultyEng { get; set; }
        public string FacultyArb { get; set; }
        public string AboutEng { get; set; }
        public string AboutArb { get; set; }
        public byte[] logo { get; set; }
        public int City { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string FacultyURL { get; set; }
        public int AdmissionType { get; set; }
        public int Hybird { get; set; }
        public int UniversityID { get; set; }
    
        public virtual AdmissionType AdmissionType1 { get; set; }
        public virtual City City1 { get; set; }
        public virtual Hybird Hybird1 { get; set; }
        public virtual ICollection<FacultyComment> FacultyComments { get; set; }
        public virtual University University { get; set; }
        public virtual ICollection<Program> Programs { get; set; }
    }
}
