//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.ProgramComments = new HashSet<ProgramComment>();
            this.Diciplines = new HashSet<Dicipline>();
        }
    
        public long ProgramID { get; set; }
        public string ProgramEng { get; set; }
        public string ProgramArb { get; set; }
        public string AboutEng { get; set; }
        public string AboutArb { get; set; }
        public decimal Period { get; set; }
        public int Semesters { get; set; }
        public string ProgramURL { get; set; }
        public long FacultyID { get; set; }
        public int DegreeID { get; set; }
    
        public virtual ICollection<ProgramComment> ProgramComments { get; set; }
        public virtual ICollection<Dicipline> Diciplines { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Degree Degree { get; set; }
    }
}
