//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniGuide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniGuideEntities : DbContext
    {
        public UniGuideEntities()
            : base("name=UniGuideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmissionType> AdmissionTypes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<Dicipline> Diciplines { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FacultyComment> FacultyComments { get; set; }
        public virtual DbSet<Hybird> Hybirds { get; set; }
        public virtual DbSet<ProgramComment> ProgramComments { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<UniversityComment> UniversityComments { get; set; }
    }
}
